version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: 21780Amit
      POSTGRES_USER: postgres
      POSTGRES_DB: mathmate-docker
    expose:
      - '5432'
    ports:
      - '5432:5432'
