version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    container_name: mathmate-dev
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: mathmate
    expose:
      - '5000'
    ports:
      - '5000:5432'
  db-test:
    image: postgres:15
    restart: always
    container_name: mathmate-test
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: mathmate-test
    expose:
      - '5555'
    ports:
      - '5555:5432'
