version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    ports:
      - 5434:5432
    container_name: mathmate-dev
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: mathmate

  db-test:
    image: postgres:15
    restart: always
    ports:
      - 5435:5432
    container_name: mathmate-test
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: postgres
      POSTGRES_DB: mathmate-test
