export const mathSubjects = [
  'Algebra',
  'Calculus',
  'Geometry',
  'Trigonometry',
  'Linear Algebra',
  'Differential Equations',
  'Probability and Statistics',
  'Combinatorics',
  'Number Theory',
  'Topology',
  'Abstract Algebra',
  'Analysis',
  'Logic',
  'Number Systems',
  'Set Theory',
  'Graph Theory',
  'Combinatorial Game Theory',
  'Number Systems',
  'Fractals and Chaos Theory',
];
